In [2]:
# 2.Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

import numpy as np

list1 = [10.0,20,30,40.04,50,60,70,80.887,90]
print("Original List:", list1)

# Convert to array
array1 = np.array(list1)
print("Converted 1D Numpy Array:", array1)


Original List: [10.0, 20, 30, 40.04, 50, 60, 70, 80.887, 90]
Converted 1D Numpy Array: [10.    20.    30.    40.04  50.    60.    70.    80.887 90.   ]


In [3]:
# 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

import numpy as np

array1D = np.arange(2,11).reshape(3,3)
print(array1D)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
# 5.Write a NumPy program to create an array with values ranging from 12 to 38.

import numpy as np

array1 = np.arange(12,38)       # Starts from 12 and ends at 37
print(array1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [6]:
# 6.Write a NumPy program to reverse an array (first element becomes last).

import numpy as np

array1 = np.arange(10,30)
print("Original Array:", array1)

# Make Reverse Array
reversed_array = array1[::-1]
print("Reversed Array:", reversed_array)

Original Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Reversed Array: [29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
# 7.Write a NumPy program to convert an array to a float type.

import numpy as np

array1 = np.arange(10,30)
print("Original Array:", array1)

# Convert the array to float type
float_array = np.asfarray(array1)
print("Converted Array:", float_array)

Original Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Converted Array: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29.]


In [13]:
# 9.Write a NumPy program to add a border (filled with 0's) around an existing array.

import numpy as np

array1 = np.ones((3,3))
print("Original Array:")
print(array1)

# Add a border filled with 0's
filled_array = np.pad(array1, pad_width=1, mode='constant', constant_values=0)
print('0 filled array:')
print(filled_array)

Original Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 filled array:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# 10.Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

import numpy as np

array1 = np.ones((5,5))
array1 = np.zeros((8,8), dtype=int)
print("Checkboard Pattern")
array1[1::2,::2] = 1
array1[::2,1::2] = 1
print(array1)

Checkboard Pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
# 11.Write a NumPy program to convert a list and tuple into arrays.

import numpy as np
import warnings

my_list = [1,2,3,4,5,6,7]
my_tuple = ([1,3,5,7],[2,4,6])

# Convert list to array
print("List to Array:", np.asarray(my_list))

# Convert tuple to array
print("Tuple to Array:", np.asarray(my_tuple))
ignore_warnings = True

List to Array: [1 2 3 4 5 6 7]
Tuple to Array: [list([1, 3, 5, 7]) list([2, 4, 6])]


C:\Users\AbsSayem\AppData\Local\Temp/ipykernel_2628/2793778486.py:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("Tuple to Array:", np.asarray(my_tuple))


In [30]:
# 12.Write a NumPy program to append values to the end of an array.

import numpy as np

x = [10, 20, 30]
print("Original Array:", x)

# Add values to the end of the array
x = np.append(x, [[40,50,60,70,80,90]])
print("After Append Values:", x)

y = np.append(x, [[100,110],[120,130,140,150]])
print("After Adding Values:", y)

Original Array: [10, 20, 30]
After Append Values: [10 20 30 40 50 60 70 80 90]
After Adding Values: [10 20 30 40 50 60 70 80 90 list([100, 110]) list([120, 130, 140, 150])]


In [32]:
# 14.Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. 
# Centigrade values are stored into a NumPy array.

import numpy as np

fvalues = [0, 12, 45, 78, 33, 99.91, 100.3]
# Convert the list into array
f = np.array(fvalues)
print("Values in Fahrenheit:", f)

c = (5*f/9 - 5*32/9)
print("Values in Centigrade:", c)

Values in Fahrenheit: [  0.    12.    45.    78.    33.    99.91 100.3 ]
Values in Centigrade: [-17.77777778 -11.11111111   7.22222222  25.55555556   0.55555556
  37.72777778  37.94444444]


In [34]:
# 15.Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

import numpy as np

x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original Array of X:", x)
print("Original Array of Y:", y)

print("Real part of X:", x.real)
print("Real part of Y:", y.real)

print("Imeginary part of X:", x.imag)
print("Imeginary part of Y:", y.imag)

Original Array of X: [1.+0.j]
Original Array of Y: [0.70710678+0.70710678j]
Real part of X: [1.]
Real part of Y: [0.70710678]
Imeginary part of X: [0.]
Imeginary part of Y: [0.70710678]


In [3]:
# 17.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

import numpy as np

array1 = np.array([0,10,20,30,33])
print("Array1:",array1)
array2 = np.array([11,20,30,40,50])
print("Array2:",array2)

print("Compare elements of both array:")
print(np.in1d(array1,array2))
print(np.in1d(array2,array1))

Array1: [ 0 10 20 30 33]
Array2: [11 20 30 40 50]
Compare elements of both array:
[False False  True  True False]
[False  True  True False False]


In [5]:
# 18.Write a NumPy program to find common values between two arrays.

import numpy as np

array1 = np.array([0,10,20,30,33])
print("Array1:",array1)
array2 = np.array([11,20,30,40,50])
print("Array2:",array2)

print("Common values between two arrays:")
print(np.intersect1d(array1,array2))

Array1: [ 0 10 20 30 33]
Array2: [11 20 30 40 50]
Common values between two arrays:
[20 30]


In [12]:
# 19.Write a NumPy program to get the unique elements of an array.

import numpy as np

array1 = np.array([10,10,20,22,30,30,44])
print("Original Array:",array1)
print("Unique elements of the above array:",np.unique(array1))

array2 = np.array([[1,1,2],[2,3,4]])
print("Original Array:")
print(array2)
print("Unique elements of the above array:",np.unique(array2))

Original Array: [10 10 20 22 30 30 44]
Unique elements of the above array: [10 20 22 30 44]
Original Array:
[[1 1 2]
 [2 3 4]]
Unique elements of the above array: [1 2 3 4]


In [13]:
# 20.Write a NumPy program to find the set difference of two arrays. 
# The set difference will return the sorted, unique values in array1 that are not in array2.

import numpy as np

array1 = np.array([0,10,20,50,80,90])
print("Array1:",array1)
array2 = np.array([30,10,20,60,70,90])
print("Array2:",array2)

print("Unique values in Array1 that are not in Array2:")
print(np.setdiff1d(array1,array2))

Array1: [ 0 10 20 50 80 90]
Array2: [30 10 20 60 70 90]
Unique values in Array1 that are not in Array2:
[ 0 50 80]


In [15]:
# 21. Write a NumPy program to find the set exclusive-or of two arrays. 
# Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

import numpy as np

array1 = np.array([0,10,20,50,80,90])
print("Array1:",array1)
array2 = np.array([30,10,20,60,70,90])
print("Array2:",array2)

print("Unique values that are in only one array:")
print(np.setxor1d(array1, array2))

Array1: [ 0 10 20 50 80 90]
Array2: [30 10 20 60 70 90]
Unique values that are in only one array:
[ 0 30 50 60 70 80]


In [16]:
# 22.Write a NumPy program to find the union of two arrays. 
# Union will return the unique, sorted array of values that are in either of the two input arrays.

import numpy as np

array1 = np.array([0,10,20,50,80,90])
print("Array1:",array1)
array2 = np.array([30,10,20,60,70,90])
print("Array2:",array2)

print("Union of two Arrays:")
print(np.union1d(array1,array2))

Array1: [ 0 10 20 50 80 90]
Array2: [30 10 20 60 70 90]
Union of two Arrays:
[ 0 10 20 30 50 60 70 80 90]


In [17]:
# 25.Write a NumPy program to construct an array by repeating.

import numpy as np

array1 = np.array([0,10,20,30,40,50])
print("Original Array:",array1)

print("Repeating 2 Times:")
print(np.tile(array1,2))
print("Repeating 3 Times:")
print(np.tile(array1,3))

Original Array: [ 0 10 20 30 40 50]
Repeating 2 Times:
[ 0 10 20 30 40 50  0 10 20 30 40 50]
Repeating 3 Times:
[ 0 10 20 30 40 50  0 10 20 30 40 50  0 10 20 30 40 50]


In [20]:
# 26.Write a NumPy program to repeat elements of an array.

import numpy as np

array1 = np.repeat(3,4)
print("Array1:",array1)

array2 = np.array([[2,3],[3,4]])
print("Repeated Array:", np.repeat(array2,2))

Array1: [3 3 3 3]
Repeated Array: [2 2 3 3 3 3 4 4]


In [2]:
# 27.Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

import numpy as np

array1 = np.array([10,0,20,30,40,50])
print("Original Array:", array1)

print("Index of Maximum Value:", np.argmax(array1))
print("Index of Minimum Value:", np.argmin(array1))

Original Array: [10  0 20 30 40 50]
Index of Maximum Value: 5
Index of Minimum Value: 1


In [7]:
# 28.Write a NumPy program compare two given arrays.

import numpy as np

array1 = np.array([1,3])
print("Array1:", array1)
array2 = np.array([2,4])
print("Array2:", array2)

print("--Is array1 > array2--")
print(np.greater(array1,array2))

print("--Is array1 >= array2--")
print(np.greater_equal(array1,array2))

print("--Is array1 < array2--")
print(np.less(array1,array2))

print("--Is array1 <= array2--")
print(np.less_equal(array1,array2))

Array1: [1 3]
Array2: [2 4]
--Is array1 > array2--
[False False]
--Is array1 >= array2--
[False False]
--Is array1 < array2--
[ True  True]
--Is array1 <= array2--
[ True  True]


In [11]:
# 31.Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

import numpy as np

array1 = np.array([100,80,10,20,30,40,50])
print("Original Array:", array1)

print("Values bigger than 10:", array1[array1>10])
print("Their indices are:", np.nonzero(array1>10))

Original Array: [100  80  10  20  30  40  50]
Values bigger than 10: [100  80  20  30  40  50]
Their indices are: (array([0, 1, 3, 4, 5, 6], dtype=int64),)


In [12]:
# 32.Write a NumPy program to save a NumPy array to a text file.

import numpy as np

array1 = np.array([1.0,2.9,56.35,0.9,20])
np.savetxt('file.txt',array1,delimiter=',')

In [10]:
# 35.Write a NumPy program to change the dimension of an array.

import numpy as np

array1 = np.array([1,2,3,4,5,6])
print("Original Array(6R,0C):")
print(array1.shape)

array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array(3R,3C):")
print(array2)

# Change the dimension
print("Changing 1D array1 to the shape(3x2)->3R,2C:")
array1.shape=(3,2)
print(array1)


Original Array(6R,0C):
(6,)
Original Array(3R,3C):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Changing 1D array1 to the shape(3x2)->3R,2C:
[[1 2]
 [3 4]
 [5 6]]


In [13]:
# 36.Write a NumPy program to create a contiguous flattened array.

import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array(3R,3C):")
print(array1)

# Make flatten
flattened_array = np.ravel(array1)
print("Flattened Array:")
print(flattened_array)

Original Array(3R,3C):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [16]:
# 38.Write a NumPy program to create a new shape to an array without changing its data.

import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("Original Array(3R,3C):")
print(array1)

# Reshape the array
print("Reshaping 3x4 array into 6x2:")
reshaped_array = np.reshape(array1,(2,6))
print(reshaped_array)

Original Array(3R,3C):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaping 3x4 array into 6x2:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [20]:
# 40.Write a NumPy program to create a new array of 3*5, filled with 2.

import numpy as np

# Using np.full
array1 = np.full((5,5), 2, dtype=np.uint)
print("Array1:", array1)

# Using np.ones
array2 = np.ones([5,5], dtype=np.uint)*2
print("Array2:", array2)

# Using np.zeros
array3 = np.zeros([5,5], dtype=np.uint)+2
print("Array3:", array3)

Array1: [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Array2: [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Array3: [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
